"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { Wand2, Download, Loader2, RefreshCw, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { generateFixedDiagram } from "@/lib/api";
import { toast } from "sonner";

interface FixedDiagramProps {
  analysisId: string;
  diagramName?: string | null;
}

export function FixedDiagram({ analysisId, diagramName }: FixedDiagramProps) {
  const [mermaidCode, setMermaidCode] = useState<string | null>(null);
  const [provider, setProvider] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [showPanel, setShowPanel] = useState(false);
  const diagramRef = useRef<HTMLDivElement>(null);

  const renderMermaid = useCallback(async (code: string) => {
    if (!diagramRef.current) return;
    try {
      const mermaid = (await import("mermaid")).default;
      mermaid.initialize({
        startOnLoad: false,
        theme: "dark",
        themeVariables: {
          primaryColor: "#06b6d4",
          primaryTextColor: "#e2e8f0",
          primaryBorderColor: "#0891b2",
          lineColor: "#64748b",
          secondaryColor: "#7c3aed",
          tertiaryColor: "#1e293b",
          background: "#0f172a",
          mainBkg: "#1e293b",
          nodeBorder: "#0891b2",
          clusterBkg: "#1e293b80",
          clusterBorder: "#334155",
          titleColor: "#e2e8f0",
          edgeLabelBackground: "#1e293b",
        },
        flowchart: { curve: "basis", padding: 15 },
      });
      const id = `mermaid-fixed-${Date.now()}`;
      const { svg } = await mermaid.render(id, code);
      diagramRef.current.innerHTML = svg;
    } catch {
      if (diagramRef.current) {
        diagramRef.current.innerHTML = `<pre class="text-xs text-red-400 p-4 whitespace-pre-wrap">${code}</pre>`;
      }
    }
  }, []);

  useEffect(() => {
    if (mermaidCode && showPanel) {
      renderMermaid(mermaidCode);
    }
  }, [mermaidCode, showPanel, renderMermaid]);

  const handleGenerate = async () => {
    setLoading(true);
    setShowPanel(true);
    try {
      const result = await generateFixedDiagram(analysisId, diagramName);
      setMermaidCode(result.mermaid);
      setProvider(result.provider);
      toast.success("Corrected diagram generated!");
    } catch {
      toast.error("Failed to generate corrected diagram. Please try again.");
      setShowPanel(false);
    } finally {
      setLoading(false);
    }
  };

  const handleExportPdf = async () => {
    if (!diagramRef.current) return;
    try {
      const html2canvas = (await import("html2canvas-pro")).default;
      const { jsPDF } = await import("jspdf");

      const canvas = await html2canvas(diagramRef.current, {
        backgroundColor: "#0f172a",
        scale: 2,
      });

      const imgData = canvas.toDataURL("image/png");
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;

      const isLandscape = imgWidth > imgHeight;
      const pdf = new jsPDF({
        orientation: isLandscape ? "landscape" : "portrait",
        unit: "px",
        format: [imgWidth + 80, imgHeight + 120],
      });

      pdf.setFontSize(20);
      pdf.setTextColor(6, 182, 212);
      const title = `ArchLens - Fixed Architecture: ${diagramName ?? "Diagram"}`;
      pdf.text(title, 40, 40);

      pdf.setFontSize(10);
      pdf.setTextColor(148, 163, 184);
      pdf.text(`Generated by ${provider ?? "AI"} | ${new Date().toLocaleDateString()}`, 40, 60);

      pdf.addImage(imgData, "PNG", 40, 80, imgWidth, imgHeight);

      const safeName = (diagramName ?? "diagram").replace(/[^a-zA-Z0-9-_]/g, "_");
      pdf.save(`archlens-fixed-${safeName}.pdf`);
      toast.success("PDF exported successfully!");
    } catch {
      toast.error("Failed to export PDF.");
    }
  };

  if (!showPanel) {
    return (
      <Button
        onClick={handleGenerate}
        disabled={loading}
        className="gap-2 bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-600 hover:to-purple-700 text-white shadow-lg shadow-purple-500/20"
      >
        {loading ? (
          <Loader2 className="h-4 w-4 animate-spin" />
        ) : (
          <Wand2 className="h-4 w-4" />
        )}
        Fix & Export Diagram
      </Button>
    );
  }

  return (
    <Card className="border-primary/30 relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/[0.03] to-purple-500/[0.03] pointer-events-none" />
      <CardHeader className="flex flex-row items-center justify-between pb-3">
        <CardTitle className="flex items-center gap-2 text-sm">
          <Wand2 className="h-4 w-4 text-primary" />
          Corrected Architecture Diagram
        </CardTitle>
        <div className="flex items-center gap-2">
          {provider && (
            <Badge variant="secondary" className="text-[10px]">
              {provider}
            </Badge>
          )}
          <Button
            variant="outline"
            size="sm"
            className="h-7 gap-1 text-xs"
            onClick={handleGenerate}
            disabled={loading}
          >
            <RefreshCw className={`h-3 w-3 ${loading ? "animate-spin" : ""}`} />
            Regenerate
          </Button>
          <Button
            variant="outline"
            size="sm"
            className="h-7 gap-1 text-xs"
            onClick={handleExportPdf}
            disabled={loading || !mermaidCode}
          >
            <Download className="h-3 w-3" />
            Export PDF
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="h-7 w-7"
            onClick={() => setShowPanel(false)}
          >
            <X className="h-3.5 w-3.5" />
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {loading ? (
          <div className="flex flex-col items-center gap-3 py-16">
            <div className="relative">
              <Loader2 className="h-10 w-10 animate-spin text-primary" />
              <div className="absolute inset-0 h-10 w-10 animate-ping rounded-full bg-primary/10" />
            </div>
            <p className="text-sm text-muted-foreground">
              AI is generating the corrected diagram...
            </p>
          </div>
        ) : (
          <div
            ref={diagramRef}
            className="flex justify-center overflow-x-auto rounded-lg bg-slate-900/50 p-4 min-h-[300px] [&_svg]:max-w-full"
          />
        )}
      </CardContent>
    </Card>
  );
}
